### ISSUE TITLE
React Hook useEffect 

### ISSUE THREAD

**Issue by GreenQuid** [thirdweb-example/erc20-staking-app#6]
at index.js i get this warning when i try next build 

warning :React Hook useEffect has a missing dependency: 'refetchData' either include it or remove the dependency array.  /exhaustive-deps 

the app compile successfully but fail as data collection take so long anyway could you help me i followed your blog as i used thirdweb staking contract

**Comment by piyushjha0409** [comment]
I would like to take this issue, seems like some nominal problem.

**Comment by avneesh0612** [comment]
Couldn't replicate this error, should be fixed!
